title: Jekyll based Web-site
author: Wispring
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  A web/blog-site made using the Jekyll framework.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Wispring # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
